global:
  resolve_timeout: 5m

route:
  receiver: jenkins-rollback-webhook
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
  - name: jenkins-rollback-webhook
    webhook_configs:
      - url: 'http://EC2_IP_PLACEHOLDER:8080/generic-webhook-trigger/invoke?token=ROLLBACK_A87B89_TOKEN'
        http_config:
          basic_auth:
            username: 'admin'
            password: 'JENKINS_API_TOKEN_PLACEHOLDER'
        send_resolved: false
